### PR TITLE
Hotfix for specialization groups bug

### LINKED ISSUE #214: Hotfix for SGS replacement issue

### PR DESCRIPTION
**Pull request by liadaram1**
The long term solution would be the refactor for each course bank to hold its own course list.

Closes #214

### CODE REVIEW

File: packages/server/src/core/bank_rule/specialization_groups.rs [hunk 1]
```diff
@@ -212,34 +212,84 @@ impl<'a> BankRuleHandler<'a> {
...
+        let find_replacement =
+            |replacements: &HashMap<String, Vec<String>>, course_id: &CourseId| -> Option<String> {
+                replacements
+                    .iter()
+                    .find_map(|(course_id_in_sg, course_id_in_sg_replacements)| {
+                        if course_id_in_sg_replacements.contains(course_id) {
+                            Some(course_id_in_sg.clone())
+                        } else {
+                            None
+                        }
```
Comment (benny-n) [inline packages/server/src/core/bank_rule/specialization_groups.rs:225]: This block
```rust
if course_id_in_sg_replacements.contains(course_id) {
    Some(course_id_in_sg.clone())
} else {
    None
}
```
Can be turned into
```rust
course_id_in_sg_replacements.contains(course_id).then(|| course_id_in_sg.clone())
```
